version: '3'
services:
  ganache:
    build: ./ganache
    container_name: ganache
    tty: true
    stdin_open: true
    volumes:
      - ./ganache:/app
    ports:
      - "7545:7545"
  bootstrap:
    build: ./bootstrap
    container_name: bootstrap
    tty: true
    stdin_open: true
    volumes:
      - ./bootstrap:/app
      - /app/target
    ports:
      - "3000:3000"
  node:
    build: ./node
    container_name: node
    tty: true
    stdin_open: true
    volumes:
      - ./node:/app
      - ./ganache/sample:/app/sample
      - ./ganache/build:/app/build
      - /app/node_modules
      - /app/lib
