version: '3'
services:
  ganache:
    build: ./ganache
    container_name: ganache
    tty: true
    stdin_open: true
    ports:
      - "7545:7545"
  contracts:
    build: ./contracts
    container_name: contracts
    tty: true
    stdin_open: true
