name: Node.js CI

on:
  push:
    branches:
      - master
jobs:
  build:
    docker:
      - image: circleci/node:12.11.0
    steps:
      - checkout
      - run:
          name: Install dependency
          command: |
            sudo npm i -g --loglevel=silent --unsafe-perm=true --allow-root ganache-cli@6.8.1
      - run:
          name: Unit Test
          command: |
            ganache-cli -m="belt prize arrow cabbage banner proof word above ability helmet design rely" --networkId=5777 -p 7545 -h 0.0.0.0 &
            cd contract
            npm run test
